### ISSUE TITLE
Add pride of Mandalore obstacles 

### ISSUE THREAD

**Issue by grandpajive** [sampson-matt/FlyCasual#10]
Hi. Thank you for contributing to and extending Sandrams effort.

It's really really nice to be able to import 2.5 xws lists, and work with them. 

I pull from meta lists (sometimes), and whenever a pride of Mandalore obstacle is in the xws, I receive "an error has occurred while creating the squad. Then it crashes.

I have a workaround, just edit the xws  with non Mando obstacles, and it works.

If you have higher priorities (which it looks like you do), is there a way you could auto generate the default obstacles instead of crashing?

I appreciate your hard work.

**Comment by sampson-matt** [comment]
Sorry for the delay in getting back to you. I'm planning to add these for my next release.

**Comment by sampson-matt** [comment]
These are included in the current release.
