### ISSUE TITLE
The Child. Game stuck.

### ISSUE THREAD

**Issue by Brigada75** [sampson-matt/FlyCasual#19]
Game hangs when The Child takes damage and he's about to recharge +1 Force.
<img width="2032" alt="Screenshot 2023-03-21 at 22 31 49" src="https://user-images.githubusercontent.com/128546232/226747128-2560f673-3788-4b20-b835-9f9f4063bf3a.png">

**Comment by sampson-matt** [comment]
This has been a long time coming, but I think I finally have this fixed. The fix will be included in my next release.
