### ISSUE TITLE
Commandant Goran (Empire, tie/in) has old ability 

### ISSUE THREAD

**Issue by grandpajive** [sampson-matt/FlyCasual#20]
His ability still allows a bump red focus instead of:

At the start of the Engagement Phase, choose a friendly ship at range 0-3 with a lower initiative than yours. The chosen ship gains 1 evade token and removes 1 non-stress red token.

**Comment by sampson-matt** [comment]
These should all be fixed now. The issue was that the source for card images was showing the errata'd pilots from 2.5 rather than the original 2.0 pilots.

**Comment by grandpajive** [comment]
Will his 'new' ability added?
