### ISSUE TITLE
Gar Saxon (Gunner/Scum) does not ask to remove red/orange token

### ISSUE THREAD

**Issue by grandpajive** [sampson-matt/FlyCasual#21]
Tried with Manaroo and also a VY666 against an enemy ship with a stress token. Gar Saxon trigger did not occur.

**Comment by sampson-matt** [comment]
Thanks! It looks like it has something to do with the arc type of those ships (full front for the VY666 and turret for the Jumpmaster). I'll try to get it fixed for the next update.

**Comment by grandpajive** [comment]
I am wrong about the yv666, it has a full front attack.

Thank you for your hard work!

**Comment by sampson-matt** [comment]
Fix for this is coded and will be included in the next release
