### ISSUE TITLE
Pilot icon selection error

### ISSUE THREAD

**Issue by synthetix808** [sampson-matt/FlyCasual#25]
Went to define pilot name and icon and got an error. 

<img width="1800" alt="Screenshot 2023-11-08 at 1 23 50 AM" src="https://github.com/sampson-matt/FlyCasual/assets/32894716/e9dade7d-704d-47aa-aabd-45e5a869596b">

**Comment by sampson-matt** [comment]
Thanks for pointing this out! I found the issue, and it will be fixed in the next release.

**Comment by sampson-matt** [comment]
this should be fixed now as of today's release
