### ISSUE TITLE
Tie Reaper/Tie Striker - Change Adaptive Ailerons to Controlled Ailerons

### ISSUE THREAD

**Issue by grandpajive** [sampson-matt/FlyCasual#27]
Tie Reapers Ailerons are now a may instead of a must. The "boost" is allowed [when not stressed], but if it fails, the ship is placed back to its starting position, then executes its maneuver. 

Tie Strikers Adaptive Ailerons are a now forced boost [unless stressed] [unless Dutchess]. they must perform their boost, but if it fails, they are placed back to their starting position, then execute their maneuver. 

Appreciate all the work you do.

**Comment by sampson-matt** [comment]
These changes were not picked up by the Legacy team, so they won't be incorporated in this version of Fly Casual.
