### ISSUE TITLE
Hard point upgrades (m3a interceptor)


### ISSUE THREAD

**Issue by grandpajive** [sampson-matt/FlyCasual#28]
Serissu and Quinn Jast (scum, m3a) have an additional cannon slot along with weapons hard point. 

At this time, I cannot equip a cannon and mag pulse warheads on either.

I'm not sure if legacy follows along with AMG slots or not. If not, ignore.

**Comment by sampson-matt** [comment]
The Legacy points document doesn't include the extra slot.
