### ISSUE TITLE
Nullref with Buzz Droids

### ISSUE THREAD

**Issue by HazelnutCookie** [sampson-matt/FlyCasual#31]
![image](https://github.com/sampson-matt/FlyCasual/assets/88517008/00a994b0-7279-4c1b-a4c7-995e7107dae3)
I clicked on my Buzz Droid Swarm after the shooting phase, and it highlighted the enemy ships to click on. When I clicked on the one closest to the Buzz Droid Swarm, it threw this NullRef. Caused no actual issues other than the nullref.

**Comment by sampson-matt** [comment]
I think I might have this fixed. I was able to duplicate the problem, and my change seemed to prevent it on my end. The fix will be included in my next update.
Thanks for reporting this!
