### ISSUE TITLE
Resistance Y-wings illicit slot

### ISSUE THREAD

**Issue by SairFecht** [sampson-matt/FlyCasual#33]
There's a couple of spice running unique resistance y-wing pilots whould should have an illict slot.

The generic Kimji Spice Runner has it's illicit slot, but Corus Kapellim and Zorii Bliss are meant to have them too.

If for nothing else so they can take Babu Frik

Cheers!

**Comment by sampson-matt** [comment]
This should be fixed as of the latest release
