### ISSUE TITLE
Buzz droids shouldnt be able to overlap other buzz droids

### ISSUE THREAD

**Issue by SairFecht** [sampson-matt/FlyCasual#34]
Buzz droids seem to be working well, but as far as I understand there are a couple of things not triggering.

Firstly, when they overlap a ship after being launched (before they've used any of the repositioning to front or back guides rules) they are still at range 0, so should still get to engage that turn.

Secondly, when they reposition onto back or front guides, they can't overlap an object - which includes other buzz droids.

Currently they game is allowing them to be stacked - I ended up with a stack of all three.

Thanks again to everyone contributing to this game!

**Comment by sampson-matt** [comment]
This should be fixed as of the latest release
