### ISSUE TITLE
Reaper squadron scout initiative 

### ISSUE THREAD

**Issue by SairFecht** [sampson-matt/FlyCasual#4]
Reaper squadron scouts (clone z-95s) are the wrong initiative - should be 3, but in game they are only initiative 2.

Thanks for the great work!

![Screenshot (7)](https://user-images.githubusercontent.com/80194625/207309833-415015f5-d214-41fe-82c3-9e8dfec944f8.png)

**Comment by sampson-matt** [comment]
Thanks! The fix for this is coded and will be included in the next release.
